#!/bin/bash

FN=$1
UN=$(whoami)
DN=$(echo $FN | awk -F.tar '{print $1}')

usage()
{
   echo "usage:  $0 <filename>" >&2
   exit 1
}

if [ -z "$FN" ]; then
   usage
fi

mkdir -p $DN
pushd $DN
sudo tar xvfz ../$FN >/dev/null 2>&1
popd
sudo chown -R $UN:$UN $DN
sudo chmod -R 775 $DN
sudo rm -f $FN

